[agent]
name = "climeai"
version = "0.0.1"
description = "Conversational weather assistant that answers weather queries in natural language. Provides current conditions, forecasts, and weather insights through interactive chat. Maintains conversation history and context for personalized weather guidance."

[options.AIML_API_KEY]
type = "string"
description = "API key for the model provider"

[options.OPENWEATHER_API_KEY]
type = "string"
description = "API key for the model provider"

[options.OPENCAGE_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MONGODB_URI]
type = "string"
description = "URI for the mongo db"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4.1')"
default = "gpt-4o"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai', etc)"
default = "openai"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
