[agent]
name = "traveladvisor"
version = "0.0.1"
description = "Multi-location travel advisor that assesses weather at origin and destination. Provides transportation-specific guidance, safety recommendations, packing suggestions, and route optimization based on weather conditions at departure and arrival times."

[options.AIML_API_KEY]
type = "string"
description = "API key for the model provider"

[options.OPENWEATHER_API_KEY]
type = "string"
description = "API key for the model provider"

[options.MODEL_NAME]
type = "string"
description = "What model to use (e.g 'gpt-4.1')"
default = "gpt-4o"

[options.MODEL_PROVIDER]
type = "string"
description = "What model provider to use (e.g 'openai', etc)"
default = "openai"

[options.MODEL_MAX_TOKENS]
type = "string"
description = "Max tokens to use"
default = "16000"

[options.MODEL_TEMPERATURE]
type = "string"
description = "What model temperature to use"
default = "0.3"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]
